"""
Live Integration Test Script for CodeMentor AI.

Executes a complete end-to-end live flow:
1. Initializes SQLite database and starts FastAPI app in-process.
2. Creates a new assignment (POST /api/questions).
3. Verifies TestCase Agent and Viva Question Agent generated draft test suite and viva bank.
4. Approves the assignment (POST /api/questions/{id}/approve).
5. Submits student Python code (POST /api/submissions).
6. Runs the 4 concurrent submission-time agents (Assessment, Mentor, Optimization, Viva).
7. Fetches the complete aggregated report (GET /api/reports/{id}).
8. Fetches classroom analytics (GET /api/analytics).
"""

import sys
import json
from fastapi.testclient import TestClient

from backend.main import app
from backend.db.session import init_db


def run_live_test():
    print("==================================================")
    print("STARTING LIVE SYSTEM INTEGRATION TEST")
    print("==================================================")

    # 1. Initialize DB with local SQLite database for instant live testing
    init_db("sqlite:///./codementor.db")
    client = TestClient(app)

    # 2. Check root status
    res = client.get("/")
    print(f"\n1. Root status check: {res.status_code} -> {res.json()}")
    assert res.status_code == 200

    # 3. Create a new Assignment draft (Faculty Flow)
    print("\n2. Faculty creates a new assignment draft (POST /api/questions)...")
    create_payload = {
        "title": "Find Two Sum Indices",
        "description": "Given an array of integers and a target sum, return indices of the two numbers that add up to target.",
        "language": "python"
    }
    res = client.post("/api/questions", json=create_payload)
    print(f"Status: {res.status_code}")
    q_data = res.json()
    print(f"Created Question ID: {q_data.get('id')}")
    print(f"Draft Test Cases Generated by TestCase Agent: {json.dumps(q_data.get('draft_tests'), indent=2)}")
    print(f"Draft Viva Questions Generated by Viva Question Agent: {json.dumps(q_data.get('draft_viva'), indent=2)}")
    assert res.status_code == 200
    q_id = q_data["id"]

    # 4. Approve Assignment
    print(f"\n3. Faculty approves assignment ID {q_id} (POST /api/questions/{q_id}/approve)...")
    res = client.post(f"/api/questions/{q_id}/approve")
    print(f"Status: {res.status_code}, Approved: {res.json().get('is_approved')}")
    assert res.status_code == 200
    assert res.json().get("is_approved") is True

    # 5. Submit Student Code (Student Flow)
    print("\n4. Student submits Python code (POST /api/submissions)...")
    student_code = (
        "def two_sum(nums, target):\n"
        "    seen = {}\n"
        "    for i, num in enumerate(nums):\n"
        "        diff = target - num\n"
        "        if diff in seen:\n"
        "            return [seen[diff], i]\n"
        "        seen[num] = i\n"
        "    return []\n"
    )
    sub_payload = {
        "assignment_id": q_id,
        "student_id": 101,
        "source_code": student_code,
        "language": "python"
    }
    res = client.post("/api/submissions", json=sub_payload)
    print(f"Status: {res.status_code}")
    sub_data = res.json()
    print(f"Submission ID: {sub_data.get('id')}, Status: {sub_data.get('status')}")
    assert res.status_code == 200
    sub_id = sub_data["id"]

    # 6. Fetch Submission Status & Report
    print(f"\n5. Fetching submission status (GET /api/submissions/{sub_id}/status)...")
    res = client.get(f"/api/submissions/{sub_id}/status")
    print(f"Status: {res.status_code}")
    status_data = res.json()
    print(f"Submission Status: {status_data.get('status')}")
    
    # 7. Inspect Multi-Agent Output in Report
    agents_output = status_data.get("details", {}).get("agents", [])
    print(f"\n6. Multi-Agent Output Pipeline ({len(agents_output)} agents returned):")
    for agent in agents_output:
        print(f"\n- Agent: {agent.get('agent_name')}")
        print(f"  Summary: {agent.get('summary')}")
        print(f"  Recommendations: {agent.get('recommendations')[:2]}")

    # 8. Fetch Classroom Analytics
    print("\n7. Fetching classroom analytics (GET /api/analytics)...")
    res = client.get("/api/analytics")
    print(f"Analytics Data: {res.json()}")

    print("\n==================================================")
    print("LIVE SYSTEM INTEGRATION TEST PASSED SUCCESSFULLY!")
    print("==================================================")


if __name__ == "__main__":
    run_live_test()
